version: '3.8'

services:
  app1:
    build:
      context: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"
    networks:
      - app_network

  app2:
    build:
      context: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"
    networks:
      - app_network

  app3:
    build:
      context: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge